version: 1.0.{build}
branches:
  only:
  - develop
  - master
  - /release/.*/
  - /hotfix/.*/
  - /feature/.*/
build_script:
- ps: .\build.ps1 -target Package

test: off

image: Visual Studio 2017

artifacts:
- path: ./artifacts/*.nupkg
